ort:
  scanner:
    storageReaders: ["fileBasedStorage"]
    storageWriters: ["fileBasedStorage"]
    storages:
      fileBasedStorage:
        backend:
          localFileStorage:
            directory: "/home/ort/.ort/scanner/scan-results"
            compression: false
    scanners:
      ScanCode:
        options:
          commandLine: "--copyright,--license,--info,--strip-root,--timeout,60,--max-depth,2,--ignore,*.test.js,--ignore,*.spec.js,--license-text"
          commandLineNonConfig: ""